image: registry.crnd.pro/crnd/docker/odoo-ci-x:13.0-simple

variables:
    SERIES_BRANCH: '13.0'
    ODOO_ADMIN_PASS: admin

    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.hidden-pip-cache"

# Disable global cache
cache: {}

.pip_cache: &pip_cache_definition
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - "${PIP_CACHE_DIR}"

stages:
    - static-test
    - test
    - translation
    - deploy

build_env:
    stage: static-test
    script:
        - pwd
        - whoami
        - python --version
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    stage: static-test
    script:
        - odoo-helper lint flake8 .
    allow_failure: true

pylint:
    stage: static-test
    script:
        - odoo-helper lint pylint  # "--license_allowed=OPL-1" .
    allow_failure: true

stylelint:
    stage: static-test
    script:
        - odoo-helper lint style .
    allow_failure: true

bandit:
    stage: static-test
    <<: *pip_cache_definition
    before_script:
        - odoo-helper pip install bandit
    script:
        - odoo-helper exec bandit -r .
    allow_failure: true

tests:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-ci
    stage: test
    <<: *pip_cache_definition
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer test --coverage --create-test-db --dir .
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    allow_failure: true

translation_rate_ua:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-ci
    stage: translation 
    <<: *pip_cache_definition
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer tr rate --lang uk_UA --min-total-rate 95 --min-addon-rate 84 --dir .
    coverage: '/^TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+|\s+(\d+\.\d+)/'
    allow_failure: true

translation_rate_ru:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-ci
    stage: translation
    <<: *pip_cache_definition
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer tr rate --lang ru_RU --min-total-rate 96 --dir .
    coverage: '/^TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+|\s+(\d+\.\d+)/'
    allow_failure: true


.deploy_review_definition: &deploy_review_definition
    stage: deploy
    variables:
    before_script:
        - ci-review-app init
    script:
        - ci-review-app start
    tags:
        - odoo-review-ci4-shared
        - review-apps
        - deploy

deploy_review_dev:
    <<: *deploy_review_definition
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: http://$CI_ENVIRONMENT_SLUG-$CI_PROJECT_ID.ci4.crnd.pro
        on_stop: stop_review_dev
    only:
        - /^13.0-.*$/   # only branches that started with '13.0-'
    when: manual

stop_review_dev:
    stage: deploy
    environment:
        name: review/$CI_COMMIT_REF_NAME
        action: stop
    variables:
        GIT_STRATEGY: none
    script:
        - ci-review-app stop
    when: manual
    tags:
        - odoo-review-ci4-shared
        - review-apps
        - deploy
    only:
        - /^13.0-.*$/   # only branches that started with '13.0-'
